---
- hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    aws_lb:
      ip: 192.168.61.20
      ports:
      - name: ingress
        source: 80
        target: 80
      - name: api
        source: 6443
        target: 6443
    aws_instances:
      host01:
        type: master
        ip: 192.168.61.21
        instance_type: t3.medium
      host02:
        type: master
        ip: 192.168.61.22
        instance_type: t3.medium
      host03:
        type: master
        ip: 192.168.61.23
        instance_type: t3.medium
  roles:
    - aws-instances
